name: 'Web3j release action'
description: 'Releases a branch'
inputs:
  version:  # id of input
    description: 'Release version'
    required: true
    default: '${{ inputs.who-to-greet }}'
runs:
  using: "composite"
  steps:
    - name: Build and stage release
      run: ./gradlew check publish bintrayUpload -Pversion=${GITHUB_REF#'release/'}
      shell: bash
    - name: Release
      run: ./gradlew closeAndReleaseRepository
      shell: bash
    - name: GitHub release
      run: ./scripts/github-release.sh
      shell: bash
    - name: Javadoc release
      run: ./gradlew -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GITHUB_TOKEN }} core:gitPublishPush
      shell: bash
