name: 'Web3j release action'
description: 'Releases a branch'
inputs:
  version:
    description: 'Release version'
    required: true
  github-token:
    description: GitHub access token
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and stage release
      run: ./gradlew check publish bintrayUpload -Pversion=${{ inputs.version }}
      shell: bash
    - name: Release
      run: ./gradlew closeAndReleaseRepository
      shell: bash
    - name: GitHub release
      run: ./scripts/github-release.sh
      shell: bash
    - name: Javadoc release
      run: ./gradlew -Dorg.ajoberstar.grgit.auth.username=${{ inputs.github-token }} core:gitPublishPush
      shell: bash
